# Generated by Django 5.1.2 on 2024-10-26 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_customuser_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
