# Generated by Django 5.1.2 on 2024-10-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='fecha_check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='fecha_check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
