# Generated by Django 5.1.2 on 2024-10-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_huesped_fecha_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='fecha_check_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
